version: 2.1
orbs:
  python: circleci/python@2.7.17
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
        -name: "sbt compile"
        -command: |
          cat /dev/null | sbt compile
workflows:
  build:
