version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
         name: "prepare"
         command: |
            sudo apt update
            sudo apt -q install -y python2-minimal ant
            ln -s /usr/bin/python2 $HOME/bin/python
      - run:
         name: "build play1"
         command: |
            sh prepare-play1.sh
      - run:
          name: "sbt compile"
          command: |
            cat /dev/null | sbt compile
workflows:
  build:
    jobs:
      - build
