version: 2.1
orbs:
  python: circleci/python@1.0.0
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
         name: "prepare"
         command: |
            sudo apt update
            sudo apt -q install -y python2-minimal ant
            ln -s /usr/bin/python2 $HOME/bin/python
      - run:
         name: "build play1"
         command: |
            sh prepare-play1.sh
            ls
            ls play1-*/framework
      - run:
          name: "sbt test for play2"
          command: |
            (cd play2app; cat /dev/null | DISPLAY=:0 sbt test)
workflows:
  build:
    jobs:
      - build
